# Generated by Django 3.0.3 on 2020-04-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
